apiVersion: v1
appVersion: 12.6.2
description: For manually running rake tasks through kubectl
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
keywords:
- gitlab
- rake
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: task-runner
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/task-runner
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-task-runner
version: 2.6.3
